apiVersion: apps/v1
kind: Deployment
metadata:
  name: coact-api
  labels:
    app: coact-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coact-api
  template:
    metadata:
      labels:
        app: coact-api
    spec:
      containers:
      - name: coact
        image: slaclab/coact:latest
        # command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--reload" ]
        command: [ "bash", "-c", "sleep infinity" ]
        env:
        - name: ADMIN_USERNAMES
          value: ytl, mshankar
        - name: MONGODB_URL
          value: mongodb://mongo-rs0-0.mongo-rs0:27017,mongo-rs0-1.mongo-rs0:27017,mongo-rs0.mongo-rs0:27017/?replicationSet=rs0
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongo
              key: COACT_USER
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: COACT_PASSWORD
        - name: PREFER_EPPN
          value: 'true'
        - name: USERNAME_FIELD
          value: x-vouch-idp-claims-name
        - name: EPPN_FIELD
          value: x-vouch-user
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: code
          mountPath: /app/
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: coact-api-code

