#!/usr/bin/env python3
"""
Compiles schema/schema.fga.yaml into:

  schema/schema.json    — compiled authorization model (loaded by sync service)
  gen/fga_relations.py  — StrEnum classes for every type's relations

Run from the openfga/ directory:
    uv run --dev python scripts/generate_fga_relations.py

Requires the `fga` CLI: https://github.com/openfga/cli
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import yaml

SCHEMA_YAML = Path(__file__).parent.parent / "schema" / "schema.fga.yaml"
SCHEMA_JSON = Path(__file__).parent.parent / "schema" / "schema.json"
GEN_DIR = Path(__file__).parent.parent / "src" / "openfga_slac" / "gen"

HEADER = """\
# AUTO-GENERATED by scripts/generate_fga_relations.py — DO NOT EDIT.
# Run: uv run python scripts/generate_fga_relations.py
"""


# ── DSL → JSON ────────────────────────────────────────────────────────────────

def dsl_to_json(dsl: str) -> dict:
    if not shutil.which("fga"):
        raise RuntimeError(
            "`fga` CLI not found. Install it from https://github.com/openfga/cli"
        )
    with tempfile.NamedTemporaryFile(suffix=".fga", mode="w", delete=False) as f:
        f.write(dsl)
        tmp = Path(f.name)
    try:
        result = subprocess.run(
            ["fga", "model", "transform", f"--file={tmp}",
             "--input-format=fga", "--output-format=json"],
            capture_output=True, text=True, check=True,
        )
        return json.loads(result.stdout)
    finally:
        tmp.unlink()


# ── Generators ────────────────────────────────────────────────────────────────

def to_class_name(type_name: str) -> str:
    """posix_group → PosixGroupRelation"""
    return "".join(p.capitalize() for p in type_name.split("_")) + "Relation"


def to_member_name(relation: str) -> str:
    """repo_admin → REPO_ADMIN"""
    return re.sub(r"[^a-zA-Z0-9]", "_", relation).upper()


def write_fga_relations(model: dict) -> None:
    blocks: list[str] = []
    for typedef in model["type_definitions"]:
        relations: dict = typedef.get("relations") or {}
        if not relations:
            continue
        lines = [f"class {to_class_name(typedef['type'])}(StrEnum):"]
        for rel in sorted(relations):
            lines.append(f'    {to_member_name(rel)} = "{rel}"')
        blocks.append("\n".join(lines))

    out = GEN_DIR / "fga_relations.py"
    out.write_text(
        HEADER + "\nfrom enum import StrEnum\n"
        + "".join(f"\n\n{b}" for b in blocks)
        + "\n"
    )
    print(f"  {out.relative_to(Path.cwd())}  ({len(blocks)} enums)")


def write_schema_json(model: dict) -> None:
    SCHEMA_JSON.write_text(json.dumps(model, indent=2) + "\n")
    print(f"  {SCHEMA_JSON.relative_to(Path.cwd())}")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    with SCHEMA_YAML.open() as f:
        yaml_data = yaml.safe_load(f)

    dsl: str = yaml_data["model"]
    print(f"Transforming DSL from {SCHEMA_YAML.name} …")
    model = dsl_to_json(dsl)

    print("Writing:")
    write_schema_json(model)
    write_fga_relations(model)
    print("Done.")


if __name__ == "__main__":
    main()
