# Generated by ariadne-codegen
# Source: queries

from .base_model import BaseModel


class AllReposAndFacility(BaseModel):
    allreposandfacility: list["AllReposAndFacilityAllreposandfacility"]


class AllReposAndFacilityAllreposandfacility(BaseModel):
    name: str
    facility: str


AllReposAndFacility.model_rebuild()
