# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class AmIRegistered(BaseModel):
    am_i_registered: "AmIRegisteredAmIRegistered" = Field(alias="amIRegistered")


class AmIRegisteredAmIRegistered(BaseModel):
    eppn: Optional[str]
    fullname: Optional[str]
    email: Optional[str]
    organization: Optional[str]
    is_registered: Optional[bool] = Field(alias="isRegistered")
    is_registration_pending: Optional[bool] = Field(alias="isRegistrationPending")
    request_id: Optional[Any] = Field(alias="requestId")
    username: Optional[str]


AmIRegistered.model_rebuild()
