# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional, Union

from .all_repos_and_facility import AllReposAndFacility
from .am_i_registered import AmIRegistered
from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .clusters import Clusters
from .facilities import Facilities
from .facilities_i_manage import FacilitiesIManage
from .facility import Facility
from .facility_name_descs import FacilityNameDescs
from .get_user_for_eppn import GetUserForEppn
from .input_types import (
    ClusterInput,
    CoactRequestFilter,
    FacilityInput,
    RepoComputeAllocationInput,
    RepoInput,
    ReportRangeInput,
    UserInput,
)
from .my_repos import MyRepos
from .my_repos_and_facility import MyReposAndFacility
from .repo_audit_trails import RepoAuditTrails
from .repo_compute_jobs import RepoComputeJobs
from .repo_features import RepoFeatures
from .report_facility_compute_by_day import ReportFacilityComputeByDay
from .report_facility_compute_by_user import ReportFacilityComputeByUser
from .report_facility_compute_overall import ReportFacilityComputeOverall
from .report_facility_storage import ReportFacilityStorage
from .repos import Repos
from .request_statuses import RequestStatuses
from .request_types import RequestTypes
from .requests import Requests
from .user_audit_trails import UserAuditTrails
from .users import Users
from .users_lookup_from_service import UsersLookupFromService
from .users_matching_user_name import UsersMatchingUserName
from .users_matching_user_names import UsersMatchingUserNames
from .whoami import Whoami


def gql(q: str) -> str:
    return q


class CoactClient(AsyncBaseClient):
    async def whoami(self, **kwargs: Any) -> Whoami:
        query = gql("""
            query Whoami {
              whoami {
                Id
                username
                fullname
                uidnumber
                eppns
                preferredemail
                shell
                publichtml
                isbot
                facilities
                isAdmin
                isCzar
                subjectFacilities
                isImpersonating
                groups
                earliestCompletedUserAccountRegistration
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="Whoami", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Whoami.model_validate(data)

    async def am_i_registered(self, **kwargs: Any) -> AmIRegistered:
        query = gql("""
            query AmIRegistered {
              amIRegistered {
                eppn
                fullname
                email
                organization
                isRegistered
                isRegistrationPending
                requestId
                username
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="AmIRegistered", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AmIRegistered.model_validate(data)

    async def users(
        self, filter_: Union[Optional[UserInput], UnsetType] = UNSET, **kwargs: Any
    ) -> Users:
        query = gql("""
            query Users($filter: UserInput) {
              users(filter: $filter) {
                Id
                username
                fullname
                uidnumber
                eppns
                preferredemail
                shell
                publichtml
                isbot
                facilities
                isAdmin
                isCzar
                subjectFacilities
                isImpersonating
                groups
                earliestCompletedUserAccountRegistration
              }
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="Users", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Users.model_validate(data)

    async def get_user_for_eppn(self, eppn: str, **kwargs: Any) -> GetUserForEppn:
        query = gql("""
            query GetUserForEppn($eppn: String!) {
              getuserforeppn(eppn: $eppn) {
                Id
                username
                fullname
                uidnumber
                eppns
                preferredemail
                shell
                publichtml
                isbot
              }
            }
            """)
        variables: dict[str, object] = {"eppn": eppn}
        response = await self.execute(
            query=query, operation_name="GetUserForEppn", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetUserForEppn.model_validate(data)

    async def users_matching_user_name(
        self, regex: str, **kwargs: Any
    ) -> UsersMatchingUserName:
        query = gql("""
            query UsersMatchingUserName($regex: String!) {
              usersMatchingUserName(regex: $regex) {
                Id
                username
                fullname
                uidnumber
                preferredemail
              }
            }
            """)
        variables: dict[str, object] = {"regex": regex}
        response = await self.execute(
            query=query,
            operation_name="UsersMatchingUserName",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UsersMatchingUserName.model_validate(data)

    async def users_matching_user_names(
        self, regexes: list[str], **kwargs: Any
    ) -> UsersMatchingUserNames:
        query = gql("""
            query UsersMatchingUserNames($regexes: [String!]!) {
              usersMatchingUserNames(regexes: $regexes) {
                Id
                username
                fullname
                uidnumber
                preferredemail
              }
            }
            """)
        variables: dict[str, object] = {"regexes": regexes}
        response = await self.execute(
            query=query,
            operation_name="UsersMatchingUserNames",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UsersMatchingUserNames.model_validate(data)

    async def clusters(
        self, filter_: Union[Optional[ClusterInput], UnsetType] = UNSET, **kwargs: Any
    ) -> Clusters:
        query = gql("""
            query Clusters($filter: ClusterInput) {
              clusters(filter: $filter) {
                Id
                name
                nodecpucount
                nodecpucountdivisor
                nodegpucount
                nodememgb
                nodegpumemgb
                chargefactor
                nodecpusmt
                members
                memberprefixes
              }
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="Clusters", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Clusters.model_validate(data)

    async def facilities(
        self, filter_: Union[Optional[FacilityInput], UnsetType] = UNSET, **kwargs: Any
    ) -> Facilities:
        query = gql("""
            query Facilities($filter: FacilityInput) {
              facilities(filter: $filter) {
                Id
                name
                description
                resources
                serviceaccount
                servicegroup
                czars
              }
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="Facilities", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Facilities.model_validate(data)

    async def facility_name_descs(self, **kwargs: Any) -> FacilityNameDescs:
        query = gql("""
            query FacilityNameDescs {
              facilityNameDescs {
                name
                description
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="FacilityNameDescs",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return FacilityNameDescs.model_validate(data)

    async def facility(
        self, filter_: Union[Optional[FacilityInput], UnsetType] = UNSET, **kwargs: Any
    ) -> Facility:
        query = gql("""
            query Facility($filter: FacilityInput) {
              facility(filter: $filter) {
                Id
                name
                description
                resources
                serviceaccount
                servicegroup
                czars
              }
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="Facility", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Facility.model_validate(data)

    async def facilities_i_manage(self, **kwargs: Any) -> FacilitiesIManage:
        query = gql("""
            query FacilitiesIManage {
              facilitiesIManage {
                Id
                name
                description
                resources
                serviceaccount
                servicegroup
                czars
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="FacilitiesIManage",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return FacilitiesIManage.model_validate(data)

    async def request_types(self, **kwargs: Any) -> RequestTypes:
        query = gql("""
            query RequestTypes {
              requestTypes
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="RequestTypes", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RequestTypes.model_validate(data)

    async def request_statuses(self, **kwargs: Any) -> RequestStatuses:
        query = gql("""
            query RequestStatuses {
              requestStatuses
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="RequestStatuses", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RequestStatuses.model_validate(data)

    async def requests(
        self,
        fetchprocessed: Union[Optional[bool], UnsetType] = UNSET,
        showmine: Union[Optional[bool], UnsetType] = UNSET,
        filter_: Union[Optional[CoactRequestFilter], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Requests:
        query = gql("""
            query Requests($fetchprocessed: Boolean, $showmine: Boolean, $filter: CoactRequestFilter) {
              requests(fetchprocessed: $fetchprocessed, showmine: $showmine, filter: $filter) {
                Id
                reqtype
                requestedby
                timeofrequest
                eppn
                username
                preferredUserName
                reponame
                facilityname
                principal
                start
                end
                clustername
                chargefactor
                storagename
                computerequirement
                purpose
                rootfolder
                allocationid
                percentOfFacility
                burstPercentOfFacility
                allocated
                burstAllocated
                gigabytes
                inodes
                shell
                previousName
                publichtml
                notes
                dontsendemail
                approvalstatus
                canapprove
                canrefire
              }
            }
            """)
        variables: dict[str, object] = {
            "fetchprocessed": fetchprocessed,
            "showmine": showmine,
            "filter": filter_,
        }
        response = await self.execute(
            query=query, operation_name="Requests", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Requests.model_validate(data)

    async def users_lookup_from_service(
        self, filter_: UserInput, **kwargs: Any
    ) -> UsersLookupFromService:
        query = gql("""
            query UsersLookupFromService($filter: UserInput!) {
              usersLookupFromService(filter: $filter) {
                Id
                username
                fullname
                uidnumber
                eppns
                preferredemail
                shell
                publichtml
                isbot
              }
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query,
            operation_name="UsersLookupFromService",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UsersLookupFromService.model_validate(data)

    async def repos(
        self, filter_: Union[Optional[RepoInput], UnsetType] = UNSET, **kwargs: Any
    ) -> Repos:
        query = gql("""
            query Repos($filter: RepoInput) {
              repos(filter: $filter) {
                Id
                state
                name
                facility
                principal
                leaders
                users
                computerequirement
                group
                description
                currentComputeAllocations {
                  Id
                  clustername
                  allocated
                  burstAllocated
                  percentOfFacility
                  burstPercentOfFacility
                }
                currentStorageAllocations {
                  Id
                  storagename
                  purpose
                  rootfolder
                  gigabytes
                  inodes
                }
              }
            }
            """)
        variables: dict[str, object] = {"filter": filter_}
        response = await self.execute(
            query=query, operation_name="Repos", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Repos.model_validate(data)

    async def my_repos(self, **kwargs: Any) -> MyRepos:
        query = gql("""
            query MyRepos {
              myRepos {
                Id
                state
                name
                facility
                principal
                leaders
                users
                computerequirement
                group
                description
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="MyRepos", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return MyRepos.model_validate(data)

    async def all_repos_and_facility(self, **kwargs: Any) -> AllReposAndFacility:
        query = gql("""
            query AllReposAndFacility {
              allreposandfacility {
                name
                facility
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="AllReposAndFacility",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return AllReposAndFacility.model_validate(data)

    async def my_repos_and_facility(self, **kwargs: Any) -> MyReposAndFacility:
        query = gql("""
            query MyReposAndFacility {
              myreposandfacility {
                name
                facility
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="MyReposAndFacility",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return MyReposAndFacility.model_validate(data)

    async def user_audit_trails(self, **kwargs: Any) -> UserAuditTrails:
        query = gql("""
            query UserAuditTrails {
              userAuditTrails {
                Id
                type
                actedon
                action
                actedby
                actedat
                details
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="UserAuditTrails", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UserAuditTrails.model_validate(data)

    async def repo_audit_trails(
        self, repo: RepoInput, **kwargs: Any
    ) -> RepoAuditTrails:
        query = gql("""
            query RepoAuditTrails($repo: RepoInput!) {
              repoAuditTrails(repo: $repo) {
                Id
                type
                actedon
                action
                actedby
                actedat
                details
              }
            }
            """)
        variables: dict[str, object] = {"repo": repo}
        response = await self.execute(
            query=query, operation_name="RepoAuditTrails", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RepoAuditTrails.model_validate(data)

    async def report_facility_compute_by_day(
        self, clustername: str, range_: ReportRangeInput, group: str, **kwargs: Any
    ) -> ReportFacilityComputeByDay:
        query = gql("""
            query ReportFacilityComputeByDay($clustername: String!, $range: ReportRangeInput!, $group: String!) {
              reportFacilityComputeByDay(
                clustername: $clustername
                range: $range
                group: $group
              ) {
                facility
                repo
                date
                resourceHours
              }
            }
            """)
        variables: dict[str, object] = {
            "clustername": clustername,
            "range": range_,
            "group": group,
        }
        response = await self.execute(
            query=query,
            operation_name="ReportFacilityComputeByDay",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ReportFacilityComputeByDay.model_validate(data)

    async def report_facility_compute_by_user(
        self, clustername: str, range_: ReportRangeInput, **kwargs: Any
    ) -> ReportFacilityComputeByUser:
        query = gql("""
            query ReportFacilityComputeByUser($clustername: String!, $range: ReportRangeInput!) {
              reportFacilityComputeByUser(clustername: $clustername, range: $range) {
                facility
                repo
                username
                resourceHours
              }
            }
            """)
        variables: dict[str, object] = {"clustername": clustername, "range": range_}
        response = await self.execute(
            query=query,
            operation_name="ReportFacilityComputeByUser",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ReportFacilityComputeByUser.model_validate(data)

    async def report_facility_compute_overall(
        self, clustername: str, group: str, **kwargs: Any
    ) -> ReportFacilityComputeOverall:
        query = gql("""
            query ReportFacilityComputeOverall($clustername: String!, $group: String!) {
              reportFacilityComputeOverall(clustername: $clustername, group: $group) {
                facility
                date
                resourceHours
              }
            }
            """)
        variables: dict[str, object] = {"clustername": clustername, "group": group}
        response = await self.execute(
            query=query,
            operation_name="ReportFacilityComputeOverall",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ReportFacilityComputeOverall.model_validate(data)

    async def report_facility_storage(
        self,
        storagename: str,
        purpose: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ReportFacilityStorage:
        query = gql("""
            query ReportFacilityStorage($storagename: String!, $purpose: String) {
              reportFacilityStorage(storagename: $storagename, purpose: $purpose) {
                facility
                repo
                storagename
                purpose
                gigabytes
                inodes
              }
            }
            """)
        variables: dict[str, object] = {"storagename": storagename, "purpose": purpose}
        response = await self.execute(
            query=query,
            operation_name="ReportFacilityStorage",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return ReportFacilityStorage.model_validate(data)

    async def repo_compute_jobs(
        self, rca: RepoComputeAllocationInput, past_x_mins: int, **kwargs: Any
    ) -> RepoComputeJobs:
        query = gql("""
            query RepoComputeJobs($rca: RepoComputeAllocationInput!, $pastXMins: Int!) {
              repoComputeJobs(rca: $rca, pastXMins: $pastXMins) {
                jobId
                username
                allocationId
                qos
                startTs
                endTs
                resourceHours
                durationMillis
                normalizedResourceHours
              }
            }
            """)
        variables: dict[str, object] = {"rca": rca, "pastXMins": past_x_mins}
        response = await self.execute(
            query=query, operation_name="RepoComputeJobs", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RepoComputeJobs.model_validate(data)

    async def repo_features(
        self, repo: str, facility: str, **kwargs: Any
    ) -> RepoFeatures:
        query = gql("""
            query RepoFeatures($repo: String!, $facility: String!) {
              repo(filter: {name: $repo, facility: $facility}) {
                name
                facility
                features {
                  name
                  state
                  options
                }
              }
              whoami {
                username
                isAdmin
                isCzar
              }
            }
            """)
        variables: dict[str, object] = {"repo": repo, "facility": facility}
        response = await self.execute(
            query=query, operation_name="RepoFeatures", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return RepoFeatures.model_validate(data)
