# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class Clusters(BaseModel):
    clusters: list["ClustersClusters"]


class ClustersClusters(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    name: Optional[str]
    nodecpucount: Optional[int]
    nodecpucountdivisor: Optional[int]
    nodegpucount: Optional[int]
    nodememgb: Optional[int]
    nodegpumemgb: Optional[int]
    chargefactor: Optional[float]
    nodecpusmt: Optional[int]
    members: Optional[list[str]]
    memberprefixes: Optional[list[str]]


Clusters.model_rebuild()
