# Generated by ariadne-codegen
# Source: http://localhost:8000/graphql

from enum import Enum


class CoactRequestType(str, Enum):
    UserAccount = "UserAccount"
    NewRepo = "NewRepo"
    RenameRepo = "RenameRepo"
    NewFacility = "NewFacility"
    RepoMembership = "RepoMembership"
    RepoRemoveUser = "RepoRemoveUser"
    RepoUpdateFeature = "RepoUpdateFeature"
    UserStorageAllocation = "UserStorageAllocation"
    RepoComputeAllocation = "RepoComputeAllocation"
    RepoStorageAllocation = "RepoStorageAllocation"
    FacilityComputeAllocation = "FacilityComputeAllocation"
    FacilityStorageAllocation = "FacilityStorageAllocation"
    RepoChangeComputeRequirement = "RepoChangeComputeRequirement"
    UserChangeShell = "UserChangeShell"
    UserPublicHtml = "UserPublicHtml"


class ComputeRequirement(str, Enum):
    OnShift = "OnShift"
    OffShift = "OffShift"
    Normal = "Normal"


class CoactRequestStatus(str, Enum):
    NotActedOn = "NotActedOn"
    Approved = "Approved"
    Rejected = "Rejected"
    Incomplete = "Incomplete"
    Completed = "Completed"
    PreApproved = "PreApproved"


class AuditTrailObjectType(str, Enum):
    User = "User"
    Repo = "Repo"
    Facility = "Facility"
