# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class Facility(BaseModel):
    facility: "FacilityFacility"


class FacilityFacility(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    name: Optional[str]
    description: Optional[str]
    resources: Optional[list[str]]
    serviceaccount: Optional[str]
    servicegroup: Optional[str]
    czars: Optional[list[str]]


Facility.model_rebuild()
