# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FacilityDetail(BaseModel):
    facility: "FacilityDetailFacility"
    past_hour: Optional[list["FacilityDetailPastHour"]] = Field(alias="pastHour")
    past_day: Optional[list["FacilityDetailPastDay"]] = Field(alias="pastDay")
    past_week: Optional[list["FacilityDetailPastWeek"]] = Field(alias="pastWeek")
    past_month: list["FacilityDetailPastMonth"] = Field(alias="pastMonth")
    ytd: list["FacilityDetailYtd"]
    lastyear: list["FacilityDetailLastyear"]
    whoami: "FacilityDetailWhoami"
    clusters: list["FacilityDetailClusters"]
    storagenames: list[str]
    storagepurposes: list[str]


class FacilityDetailFacility(BaseModel):
    name: Optional[str]
    description: Optional[str]
    czars: Optional[list[str]]
    serviceaccount: Optional[str]
    servicegroup: Optional[str]
    computepurchases: Optional[list["FacilityDetailFacilityComputepurchases"]]
    storagepurchases: Optional[list["FacilityDetailFacilityStoragepurchases"]]


class FacilityDetailFacilityComputepurchases(BaseModel):
    clustername: Optional[str]
    purchased: Optional[float]
    burst_percent: Optional[float] = Field(alias="burstPercent")
    allocated: Optional[float]


class FacilityDetailFacilityStoragepurchases(BaseModel):
    storagename: Optional[str]
    purpose: Optional[str]
    purchased: Optional[float]
    allocated: Optional[float]
    used: Optional[float]


class FacilityDetailPastHour(BaseModel):
    clustername: Optional[str]
    facility: Optional[str]
    percent_used: float = Field(alias="percentUsed")
    resource_hours: Optional[float] = Field(alias="resourceHours")


class FacilityDetailPastDay(BaseModel):
    clustername: Optional[str]
    facility: Optional[str]
    percent_used: float = Field(alias="percentUsed")
    resource_hours: Optional[float] = Field(alias="resourceHours")


class FacilityDetailPastWeek(BaseModel):
    clustername: Optional[str]
    facility: Optional[str]
    percent_used: float = Field(alias="percentUsed")
    resource_hours: Optional[float] = Field(alias="resourceHours")


class FacilityDetailPastMonth(BaseModel):
    clustername: Optional[str]
    available_resource_hours: Optional[float] = Field(alias="availableResourceHours")
    nodecpucount: Optional[float]
    percent_used: float = Field(alias="percentUsed")
    purchased: Optional[float]
    used_resource_hours: float = Field(alias="usedResourceHours")


class FacilityDetailYtd(BaseModel):
    clustername: Optional[str]
    available_resource_hours: Optional[float] = Field(alias="availableResourceHours")
    nodecpucount: Optional[float]
    percent_used: float = Field(alias="percentUsed")
    purchased: Optional[float]
    used_resource_hours: float = Field(alias="usedResourceHours")


class FacilityDetailLastyear(BaseModel):
    clustername: Optional[str]
    available_resource_hours: Optional[float] = Field(alias="availableResourceHours")
    nodecpucount: Optional[float]
    percent_used: float = Field(alias="percentUsed")
    purchased: Optional[float]
    used_resource_hours: float = Field(alias="usedResourceHours")


class FacilityDetailWhoami(BaseModel):
    username: Optional[str]
    is_admin: bool = Field(alias="isAdmin")


class FacilityDetailClusters(BaseModel):
    name: Optional[str]
    nodecpucount: Optional[int]
    nodecpucountdivisor: Optional[int]
    chargefactor: Optional[float]


FacilityDetail.model_rebuild()
FacilityDetailFacility.model_rebuild()
