# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FacilityRecentComputeUsage(BaseModel):
    facility_recent_compute_usage: Optional[
        list["FacilityRecentComputeUsageFacilityRecentComputeUsage"]
    ] = Field(alias="facilityRecentComputeUsage")


class FacilityRecentComputeUsageFacilityRecentComputeUsage(BaseModel):
    facility: Optional[str]
    clustername: Optional[str]
    resource_hours: Optional[float] = Field(alias="resourceHours")
    percent_used: float = Field(alias="percentUsed")
    purchased_nodes: Optional[int] = Field(alias="purchasedNodes")


FacilityRecentComputeUsage.model_rebuild()
