# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class FacilitiesIManage(BaseModel):
    facilities_i_manage: list["FacilitiesIManageFacilitiesIManage"] = Field(
        alias="facilitiesIManage"
    )


class FacilitiesIManageFacilitiesIManage(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    name: Optional[str]
    description: Optional[str]
    resources: Optional[list[str]]
    serviceaccount: Optional[str]
    servicegroup: Optional[str]
    czars: Optional[list[str]]


FacilitiesIManage.model_rebuild()
