# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CoactRequestStatus


class FacilityNamesWithRegistration(BaseModel):
    facility_name_descs: list["FacilityNamesWithRegistrationFacilityNameDescs"] = Field(
        alias="facilityNameDescs"
    )
    am_i_registered: "FacilityNamesWithRegistrationAmIRegistered" = Field(
        alias="amIRegistered"
    )


class FacilityNamesWithRegistrationFacilityNameDescs(BaseModel):
    name: Optional[str]
    description: Optional[str]


class FacilityNamesWithRegistrationAmIRegistered(BaseModel):
    is_registered: Optional[bool] = Field(alias="isRegistered")
    is_registration_pending: Optional[bool] = Field(alias="isRegistrationPending")
    eppn: Optional[str]
    username: Optional[str]
    fullname: Optional[str]
    request_obj: Optional["FacilityNamesWithRegistrationAmIRegisteredRequestObj"] = (
        Field(alias="requestObj")
    )


class FacilityNamesWithRegistrationAmIRegisteredRequestObj(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    approvalstatus: Optional[CoactRequestStatus]
    preferred_user_name: Optional[str] = Field(alias="preferredUserName")
    eppn: Optional[str]
    facilityname: Optional[str]
    notes: Optional[str]
    audit: Optional[list["FacilityNamesWithRegistrationAmIRegisteredRequestObjAudit"]]


class FacilityNamesWithRegistrationAmIRegisteredRequestObjAudit(BaseModel):
    notes: Optional[str]


FacilityNamesWithRegistration.model_rebuild()
FacilityNamesWithRegistrationAmIRegistered.model_rebuild()
FacilityNamesWithRegistrationAmIRegisteredRequestObj.model_rebuild()
