# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FacilityNameDescs(BaseModel):
    facility_name_descs: list["FacilityNameDescsFacilityNameDescs"] = Field(
        alias="facilityNameDescs"
    )


class FacilityNameDescsFacilityNameDescs(BaseModel):
    name: Optional[str]
    description: Optional[str]


FacilityNameDescs.model_rebuild()
