# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class Facilities(BaseModel):
    facilities: list["FacilitiesFacilities"]


class FacilitiesFacilities(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    name: Optional[str]
    description: Optional[str]
    resources: Optional[list[str]]
    serviceaccount: Optional[str]
    servicegroup: Optional[str]
    czars: Optional[list[str]]


Facilities.model_rebuild()
