# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetUserForEppn(BaseModel):
    getuserforeppn: Optional["GetUserForEppnGetuserforeppn"]


class GetUserForEppnGetuserforeppn(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    username: Optional[str]
    fullname: Optional[str]
    uidnumber: Optional[int]
    eppns: Optional[list[str]]
    preferredemail: Optional[str]
    shell: Optional[str]
    publichtml: bool
    isbot: bool


GetUserForEppn.model_rebuild()
