# Generated by ariadne-codegen
# Source: http://localhost:8000/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AuditTrailObjectType,
    CoactRequestStatus,
    CoactRequestType,
    ComputeRequirement,
)


class UserInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    username: Optional[str] = None
    fullname: Optional[str] = None
    uidnumber: Optional[int] = None
    eppns: Optional[list[str]] = None
    preferredemail: Optional[str] = None
    shell: Optional[str] = None
    publichtml: bool
    isbot: bool


class ClusterInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    name: Optional[str] = None
    nodecpucount: Optional[int] = None
    nodecpucountdivisor: Optional[int] = None
    nodegpucount: Optional[int] = None
    nodememgb: Optional[int] = None
    nodegpumemgb: Optional[int] = None
    chargefactor: Optional[float] = None
    nodecpusmt: Optional[int] = None
    members: Optional[list[str]] = None
    memberprefixes: Optional[list[str]] = None


class FacilityInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    name: Optional[str] = None
    description: Optional[str] = None
    resources: Optional[list[str]] = None
    serviceaccount: Optional[str] = None
    servicegroup: Optional[str] = None
    czars: Optional[list[str]] = None


class CoactRequestFilter(BaseModel):
    reqtype: Optional[CoactRequestType] = None
    approvalstatus: Optional[CoactRequestStatus] = None
    reponame: Optional[str] = None
    facilityname: Optional[str] = None
    windowbegin: Optional[Any] = None
    windowend: Optional[Any] = None
    foruser: Optional[str] = None


class AccessGroupInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    state: Optional[str] = None
    gidnumber: Optional[int] = None
    name: Optional[str] = None
    repoid: Optional[Any] = None
    members: Optional[list[str]] = None


class RepoInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    state: Optional[str] = None
    name: Optional[str] = None
    facility: Optional[str] = None
    principal: Optional[str] = None
    leaders: Optional[list[str]] = None
    users: Optional[list[str]] = None
    computerequirement: Optional[ComputeRequirement] = None
    group: Optional[str] = None
    description: Optional[str] = None


class ReportRangeInput(BaseModel):
    start: Optional[Any] = None
    end: Optional[Any] = None


class RepoComputeAllocationInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    repoid: Optional[Any] = None
    clustername: Optional[str] = None
    start: Optional[Any] = None
    end: Optional[Any] = None
    percent_of_facility: Optional[float] = Field(
        alias="percentOfFacility", default=None
    )
    burst_percent_of_facility: Optional[float] = Field(
        alias="burstPercentOfFacility", default=None
    )
    allocated: Optional[float] = None
    burst_allocated: Optional[float] = Field(alias="burstAllocated", default=None)


class UserStorageInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    username: Optional[str] = None
    purpose: Optional[str] = None
    gigabytes: Optional[float] = None
    inodes: Optional[float] = None
    storagename: Optional[str] = None
    rootfolder: Optional[str] = None


class CoactRequestInput(BaseModel):
    reqtype: Optional[CoactRequestType] = None
    requestedby: Optional[str] = None
    timeofrequest: Optional[Any] = None
    eppn: Optional[str] = None
    username: Optional[str] = None
    preferred_user_name: Optional[str] = Field(alias="preferredUserName", default=None)
    reponame: Optional[str] = None
    facilityname: Optional[str] = None
    principal: Optional[str] = None
    start: Optional[Any] = None
    end: Optional[Any] = None
    clustername: Optional[str] = None
    chargefactor: Optional[float] = None
    storagename: Optional[str] = None
    computerequirement: Optional[ComputeRequirement] = None
    purpose: Optional[str] = None
    rootfolder: Optional[str] = None
    allocationid: Optional[Any] = None
    percent_of_facility: Optional[float] = Field(
        alias="percentOfFacility", default=None
    )
    burst_percent_of_facility: Optional[float] = Field(
        alias="burstPercentOfFacility", default=None
    )
    allocated: Optional[float] = None
    burst_allocated: Optional[float] = Field(alias="burstAllocated", default=None)
    gigabytes: Optional[float] = None
    inodes: Optional[float] = None
    shell: Optional[str] = None
    previous_name: Optional[str] = Field(alias="previousName", default=None)
    publichtml: bool
    notes: Optional[str] = None
    dontsendemail: Optional[bool] = None
    approvalstatus: Optional[CoactRequestStatus] = None


class UserAllocationInput(BaseModel):
    allocationid: Optional[Any] = None
    username: Optional[str] = None
    percent: Optional[float] = None


class RepoStorageAllocationInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    repoid: Optional[Any] = None
    storagename: Optional[str] = None
    purpose: Optional[str] = None
    rootfolder: Optional[str] = None
    start: Optional[Any] = None
    end: Optional[Any] = None
    gigabytes: Optional[float] = None
    inodes: Optional[float] = None


class RepoFeatureInput(BaseModel):
    name: str
    state: bool
    options: Optional[list[str]] = None


class Job(BaseModel):
    job_id: Any = Field(alias="jobId")
    username: str
    allocation_id: Any = Field(alias="allocationId")
    qos: str
    start_ts: Any = Field(alias="startTs")
    end_ts: Any = Field(alias="endTs")
    resource_hours: float = Field(alias="resourceHours")


class StorageDailyUsageInput(BaseModel):
    allocationid: Optional[Any] = None
    date: Optional[Any] = None
    gigabytes: Optional[float] = None
    inodes: Optional[float] = None


class AuditTrailInput(BaseModel):
    id: Optional[Any] = Field(alias="Id", default=None)
    type_: Optional[AuditTrailObjectType] = Field(alias="type", default=None)
    actedon: Optional[Any] = None
    action: Optional[str] = None
    actedby: Optional[str] = None
    actedat: Optional[Any] = None
    details: Optional[str] = None


class NotificationInput(BaseModel):
    to: Optional[list[str]] = None
    cc: Optional[list[str]] = None
    bcc: Optional[list[str]] = None
    subject: Optional[str] = None
    body: Optional[str] = None
