# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class MyGids(BaseModel):
    my_gids: Optional["MyGidsMyGids"] = Field(alias="myGids")


class MyGidsMyGids(BaseModel):
    uidnumber: Optional[int]
    primary_gid: Optional[int] = Field(alias="primaryGid")
    secondary_gid_numbers: list[int] = Field(alias="secondaryGidNumbers")
    synced_at: Optional[Any] = Field(alias="syncedAt")


MyGids.model_rebuild()
