# Generated by ariadne-codegen
# Source: queries

from .base_model import BaseModel


class MyReposAndFacility(BaseModel):
    myreposandfacility: list["MyReposAndFacilityMyreposandfacility"]


class MyReposAndFacilityMyreposandfacility(BaseModel):
    name: str
    facility: str


MyReposAndFacility.model_rebuild()
