# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class MyReposComputeView(BaseModel):
    my_repos: list["MyReposComputeViewMyRepos"] = Field(alias="myRepos")
    whoami: "MyReposComputeViewWhoami"
    facilities: list["MyReposComputeViewFacilities"]
    clusters: list["MyReposComputeViewClusters"]
    cluster_purchases: list["MyReposComputeViewClusterPurchases"] = Field(
        alias="clusterPurchases"
    )
    past_hour: Optional[list["MyReposComputeViewPastHour"]] = Field(alias="pastHour")
    past_day: Optional[list["MyReposComputeViewPastDay"]] = Field(alias="pastDay")
    past_week: Optional[list["MyReposComputeViewPastWeek"]] = Field(alias="pastWeek")
    past_month: Optional[list["MyReposComputeViewPastMonth"]] = Field(alias="pastMonth")


class MyReposComputeViewMyRepos(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    name: Optional[str]
    facility: Optional[str]
    principal: Optional[str]
    current_compute_allocations: list[
        "MyReposComputeViewMyReposCurrentComputeAllocations"
    ] = Field(alias="currentComputeAllocations")


class MyReposComputeViewMyReposCurrentComputeAllocations(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    clustername: Optional[str]
    cluster_node_cpu_count: int = Field(alias="clusterNodeCPUCount")
    start: Optional[Any]
    end: Optional[Any]
    percent_of_facility: Optional[float] = Field(alias="percentOfFacility")
    allocated: Optional[float]
    burst_percent_of_facility: Optional[float] = Field(alias="burstPercentOfFacility")
    burst_allocated: Optional[float] = Field(alias="burstAllocated")
    usage: list["MyReposComputeViewMyReposCurrentComputeAllocationsUsage"]


class MyReposComputeViewMyReposCurrentComputeAllocationsUsage(BaseModel):
    resource_hours: Optional[float] = Field(alias="resourceHours")


class MyReposComputeViewWhoami(BaseModel):
    username: Optional[str]
    is_admin: bool = Field(alias="isAdmin")
    is_czar: bool = Field(alias="isCzar")


class MyReposComputeViewFacilities(BaseModel):
    name: Optional[str]
    computepurchases: Optional[list["MyReposComputeViewFacilitiesComputepurchases"]]


class MyReposComputeViewFacilitiesComputepurchases(BaseModel):
    purchased: Optional[float]
    clustername: Optional[str]


class MyReposComputeViewClusters(BaseModel):
    name: Optional[str]
    nodecpucount: Optional[int]


class MyReposComputeViewClusterPurchases(BaseModel):
    clustername: str
    totalpurchased: int


class MyReposComputeViewPastHour(BaseModel):
    name: Optional[str]
    clustername: Optional[str]
    facility: Optional[str]
    percent_used: float = Field(alias="percentUsed")
    resource_hours: Optional[float] = Field(alias="resourceHours")


class MyReposComputeViewPastDay(BaseModel):
    name: Optional[str]
    clustername: Optional[str]
    facility: Optional[str]
    percent_used: float = Field(alias="percentUsed")
    resource_hours: Optional[float] = Field(alias="resourceHours")


class MyReposComputeViewPastWeek(BaseModel):
    name: Optional[str]
    clustername: Optional[str]
    facility: Optional[str]
    percent_used: float = Field(alias="percentUsed")
    resource_hours: Optional[float] = Field(alias="resourceHours")


class MyReposComputeViewPastMonth(BaseModel):
    name: Optional[str]
    clustername: Optional[str]
    facility: Optional[str]
    percent_used: float = Field(alias="percentUsed")
    resource_hours: Optional[float] = Field(alias="resourceHours")


MyReposComputeView.model_rebuild()
MyReposComputeViewMyRepos.model_rebuild()
MyReposComputeViewMyReposCurrentComputeAllocations.model_rebuild()
MyReposComputeViewFacilities.model_rebuild()
