# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ComputeRequirement


class MyRepos(BaseModel):
    my_repos: list["MyReposMyRepos"] = Field(alias="myRepos")


class MyReposMyRepos(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    state: Optional[str]
    name: Optional[str]
    facility: Optional[str]
    principal: Optional[str]
    leaders: Optional[list[str]]
    users: Optional[list[str]]
    computerequirement: Optional[ComputeRequirement]
    group: Optional[str]
    description: Optional[str]


MyRepos.model_rebuild()
