# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class PosixSyncStatus(BaseModel):
    posix_sync_status: Optional["PosixSyncStatusPosixSyncStatus"] = Field(
        alias="posixSyncStatus"
    )


class PosixSyncStatusPosixSyncStatus(BaseModel):
    lastrun: Optional[Any]
    lastsuccess: Optional[Any]
    dry_run: bool = Field(alias="dryRun")
    total: int
    matched: int
    changed: int
    unknown_users: int = Field(alias="unknownUsers")
    aborted: bool
    reason: Optional[str]


PosixSyncStatus.model_rebuild()
