# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class RepoStorageDetail(BaseModel):
    repo: "RepoStorageDetailRepo"


class RepoStorageDetailRepo(BaseModel):
    name: Optional[str]
    facility: Optional[str]
    storage_allocation: Optional["RepoStorageDetailRepoStorageAllocation"] = Field(
        alias="storageAllocation"
    )


class RepoStorageDetailRepoStorageAllocation(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    storagename: Optional[str]
    purpose: Optional[str]
    start: Optional[Any]
    end: Optional[Any]
    gigabytes: Optional[float]
    usage: Optional["RepoStorageDetailRepoStorageAllocationUsage"]
    per_date_usage: list["RepoStorageDetailRepoStorageAllocationPerDateUsage"] = Field(
        alias="perDateUsage"
    )


class RepoStorageDetailRepoStorageAllocationUsage(BaseModel):
    gigabytes: Optional[float]


class RepoStorageDetailRepoStorageAllocationPerDateUsage(BaseModel):
    date: Optional[Any]
    gigabytes: Optional[float]


RepoStorageDetail.model_rebuild()
RepoStorageDetailRepo.model_rebuild()
RepoStorageDetailRepoStorageAllocation.model_rebuild()
