# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AuditTrailObjectType, CoactRequestStatus, CoactRequestType


class RepoAuditDetail(BaseModel):
    repo_audit_trails: list["RepoAuditDetailRepoAuditTrails"] = Field(
        alias="repoAuditTrails"
    )
    requests: Optional[list["RepoAuditDetailRequests"]]
    whoami: "RepoAuditDetailWhoami"


class RepoAuditDetailRepoAuditTrails(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    type_: Optional[AuditTrailObjectType] = Field(alias="type")
    action: Optional[str]
    actedby: Optional[str]
    actedat: Optional[Any]
    details: Optional[str]


class RepoAuditDetailRequests(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    reqtype: Optional[CoactRequestType]
    requestedby: Optional[str]
    timeofrequest: Optional[Any]
    approvalstatus: Optional[CoactRequestStatus]
    username: Optional[str]
    notes: Optional[str]
    audit: Optional[list["RepoAuditDetailRequestsAudit"]]


class RepoAuditDetailRequestsAudit(BaseModel):
    actedby: Optional[str]
    actedat: Optional[Any]
    notes: Optional[str]
    previous: Optional[CoactRequestStatus]


class RepoAuditDetailWhoami(BaseModel):
    username: Optional[str]


RepoAuditDetail.model_rebuild()
RepoAuditDetailRequests.model_rebuild()
