# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ReportFacilityComputeByUser(BaseModel):
    report_facility_compute_by_user: list[
        "ReportFacilityComputeByUserReportFacilityComputeByUser"
    ] = Field(alias="reportFacilityComputeByUser")


class ReportFacilityComputeByUserReportFacilityComputeByUser(BaseModel):
    facility: Optional[str]
    repo: Optional[str]
    username: Optional[str]
    resource_hours: Optional[float] = Field(alias="resourceHours")


ReportFacilityComputeByUser.model_rebuild()
