# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AuditTrailObjectType


class RepoAuditTrails(BaseModel):
    repo_audit_trails: list["RepoAuditTrailsRepoAuditTrails"] = Field(
        alias="repoAuditTrails"
    )


class RepoAuditTrailsRepoAuditTrails(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    type_: Optional[AuditTrailObjectType] = Field(alias="type")
    actedon: Optional[Any]
    action: Optional[str]
    actedby: Optional[str]
    actedat: Optional[Any]
    details: Optional[str]


RepoAuditTrails.model_rebuild()
