# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class ReportFacilityComputeByDay(BaseModel):
    report_facility_compute_by_day: list[
        "ReportFacilityComputeByDayReportFacilityComputeByDay"
    ] = Field(alias="reportFacilityComputeByDay")


class ReportFacilityComputeByDayReportFacilityComputeByDay(BaseModel):
    facility: Optional[str]
    repo: Optional[str]
    date: Optional[Any]
    resource_hours: Optional[float] = Field(alias="resourceHours")


ReportFacilityComputeByDay.model_rebuild()
