# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class RepoComputeDetail(BaseModel):
    repos: list["RepoComputeDetailRepos"]
    clusters: list["RepoComputeDetailClusters"]
    whoami: "RepoComputeDetailWhoami"


class RepoComputeDetailRepos(BaseModel):
    name: Optional[str]
    facility: Optional[str]
    users: Optional[list[str]]
    facility_obj: "RepoComputeDetailReposFacilityObj" = Field(alias="facilityObj")
    compute_allocation: Optional["RepoComputeDetailReposComputeAllocation"] = Field(
        alias="computeAllocation"
    )


class RepoComputeDetailReposFacilityObj(BaseModel):
    name: Optional[str]
    computepurchases: Optional[
        list["RepoComputeDetailReposFacilityObjComputepurchases"]
    ]


class RepoComputeDetailReposFacilityObjComputepurchases(BaseModel):
    purchased: Optional[float]
    clustername: Optional[str]


class RepoComputeDetailReposComputeAllocation(BaseModel):
    clustername: Optional[str]
    start: Optional[Any]
    end: Optional[Any]
    percent_of_facility: Optional[float] = Field(alias="percentOfFacility")
    user_allocations: list["RepoComputeDetailReposComputeAllocationUserAllocations"] = (
        Field(alias="userAllocations")
    )
    usage: list["RepoComputeDetailReposComputeAllocationUsage"]
    per_date_usage: list["RepoComputeDetailReposComputeAllocationPerDateUsage"] = Field(
        alias="perDateUsage"
    )
    per_user_usage: list["RepoComputeDetailReposComputeAllocationPerUserUsage"] = Field(
        alias="perUserUsage"
    )


class RepoComputeDetailReposComputeAllocationUserAllocations(BaseModel):
    username: Optional[str]
    percent: Optional[float]


class RepoComputeDetailReposComputeAllocationUsage(BaseModel):
    resource_hours: Optional[float] = Field(alias="resourceHours")


class RepoComputeDetailReposComputeAllocationPerDateUsage(BaseModel):
    date: Optional[Any]
    resource_hours: Optional[float] = Field(alias="resourceHours")


class RepoComputeDetailReposComputeAllocationPerUserUsage(BaseModel):
    username: Optional[str]
    resource_hours: Optional[float] = Field(alias="resourceHours")


class RepoComputeDetailClusters(BaseModel):
    name: Optional[str]
    nodecpucount: Optional[int]
    nodecpucountdivisor: Optional[int]
    chargefactor: Optional[float]


class RepoComputeDetailWhoami(BaseModel):
    username: Optional[str]
    is_admin: bool = Field(alias="isAdmin")
    is_czar: bool = Field(alias="isCzar")


RepoComputeDetail.model_rebuild()
RepoComputeDetailRepos.model_rebuild()
RepoComputeDetailReposFacilityObj.model_rebuild()
RepoComputeDetailReposComputeAllocation.model_rebuild()
