# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class ReportFacilityComputeOverall(BaseModel):
    report_facility_compute_overall: list[
        "ReportFacilityComputeOverallReportFacilityComputeOverall"
    ] = Field(alias="reportFacilityComputeOverall")


class ReportFacilityComputeOverallReportFacilityComputeOverall(BaseModel):
    facility: Optional[str]
    date: Optional[Any]
    resource_hours: Optional[float] = Field(alias="resourceHours")


ReportFacilityComputeOverall.model_rebuild()
