# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class RepoGroupsDetail(BaseModel):
    repos: list["RepoGroupsDetailRepos"]
    whoami: "RepoGroupsDetailWhoami"


class RepoGroupsDetailRepos(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    name: Optional[str]
    facility: Optional[str]
    principal: Optional[str]
    leaders: Optional[list[str]]
    all_users: list["RepoGroupsDetailReposAllUsers"] = Field(alias="allUsers")
    access_group_objs: list["RepoGroupsDetailReposAccessGroupObjs"] = Field(
        alias="accessGroupObjs"
    )


class RepoGroupsDetailReposAllUsers(BaseModel):
    username: Optional[str]


class RepoGroupsDetailReposAccessGroupObjs(BaseModel):
    name: Optional[str]
    gidnumber: Optional[int]
    member_objs: list["RepoGroupsDetailReposAccessGroupObjsMemberObjs"] = Field(
        alias="memberObjs"
    )


class RepoGroupsDetailReposAccessGroupObjsMemberObjs(BaseModel):
    username: Optional[str]


class RepoGroupsDetailWhoami(BaseModel):
    username: Optional[str]


RepoGroupsDetail.model_rebuild()
RepoGroupsDetailRepos.model_rebuild()
RepoGroupsDetailReposAccessGroupObjs.model_rebuild()
