# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class RepoFeatures(BaseModel):
    repo: "RepoFeaturesRepo"
    whoami: "RepoFeaturesWhoami"


class RepoFeaturesRepo(BaseModel):
    name: Optional[str]
    facility: Optional[str]
    features: Optional[list["RepoFeaturesRepoFeatures"]]


class RepoFeaturesRepoFeatures(BaseModel):
    name: str
    state: bool
    options: Optional[list[str]]


class RepoFeaturesWhoami(BaseModel):
    username: Optional[str]
    is_admin: bool = Field(alias="isAdmin")
    is_czar: bool = Field(alias="isCzar")


RepoFeatures.model_rebuild()
RepoFeaturesRepo.model_rebuild()
