# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ReportFacilityStorage(BaseModel):
    report_facility_storage: list["ReportFacilityStorageReportFacilityStorage"] = Field(
        alias="reportFacilityStorage"
    )


class ReportFacilityStorageReportFacilityStorage(BaseModel):
    facility: Optional[str]
    repo: Optional[str]
    storagename: Optional[str]
    purpose: Optional[str]
    gigabytes: Optional[float]
    inodes: Optional[float]


ReportFacilityStorage.model_rebuild()
