# Generated by ariadne-codegen
# Source: queries

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class RepoComputeJobs(BaseModel):
    repo_compute_jobs: list["RepoComputeJobsRepoComputeJobs"] = Field(
        alias="repoComputeJobs"
    )


class RepoComputeJobsRepoComputeJobs(BaseModel):
    job_id: Any = Field(alias="jobId")
    username: str
    allocation_id: Any = Field(alias="allocationId")
    qos: str
    start_ts: Any = Field(alias="startTs")
    end_ts: Any = Field(alias="endTs")
    resource_hours: float = Field(alias="resourceHours")
    duration_millis: Any = Field(alias="durationMillis")
    normalized_resource_hours: float = Field(alias="normalizedResourceHours")


RepoComputeJobs.model_rebuild()
