# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class RepoUsersDetail(BaseModel):
    repos: list["RepoUsersDetailRepos"]
    whoami: "RepoUsersDetailWhoami"


class RepoUsersDetailRepos(BaseModel):
    name: Optional[str]
    facility: Optional[str]
    facility_obj: "RepoUsersDetailReposFacilityObj" = Field(alias="facilityObj")
    principal: Optional[str]
    leaders: Optional[list[str]]
    users: Optional[list[str]]
    all_users: list["RepoUsersDetailReposAllUsers"] = Field(alias="allUsers")


class RepoUsersDetailReposFacilityObj(BaseModel):
    czars: Optional[list[str]]


class RepoUsersDetailReposAllUsers(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    username: Optional[str]
    uidnumber: Optional[int]
    preferredemail: Optional[str]
    fullname: Optional[str]
    eppn_objs: list["RepoUsersDetailReposAllUsersEppnObjs"] = Field(alias="eppnObjs")


class RepoUsersDetailReposAllUsersEppnObjs(BaseModel):
    eppn: Optional[str]
    fullname: Optional[str]
    organization: Optional[str]


class RepoUsersDetailWhoami(BaseModel):
    username: Optional[str]


RepoUsersDetail.model_rebuild()
RepoUsersDetailRepos.model_rebuild()
RepoUsersDetailReposAllUsers.model_rebuild()
