# Generated by ariadne-codegen
# Source: queries

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class ReportFacilityComputeByUserToDate(BaseModel):
    report_facility_compute_by_user_to_date: list[
        "ReportFacilityComputeByUserToDateReportFacilityComputeByUserToDate"
    ] = Field(alias="reportFacilityComputeByUserToDate")


class ReportFacilityComputeByUserToDateReportFacilityComputeByUserToDate(BaseModel):
    facility: Optional[str]
    repo: Optional[str]
    username: Optional[str]
    resource_hours: Optional[float] = Field(alias="resourceHours")


ReportFacilityComputeByUserToDate.model_rebuild()
