# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ComputeRequirement


class Repos(BaseModel):
    repos: list["ReposRepos"]


class ReposRepos(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    state: Optional[str]
    name: Optional[str]
    facility: Optional[str]
    principal: Optional[str]
    leaders: Optional[list[str]]
    users: Optional[list[str]]
    computerequirement: Optional[ComputeRequirement]
    group: Optional[str]
    description: Optional[str]
    current_compute_allocations: list["ReposReposCurrentComputeAllocations"] = Field(
        alias="currentComputeAllocations"
    )
    current_storage_allocations: list["ReposReposCurrentStorageAllocations"] = Field(
        alias="currentStorageAllocations"
    )


class ReposReposCurrentComputeAllocations(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    clustername: Optional[str]
    allocated: Optional[float]
    burst_allocated: Optional[float] = Field(alias="burstAllocated")
    percent_of_facility: Optional[float] = Field(alias="percentOfFacility")
    burst_percent_of_facility: Optional[float] = Field(alias="burstPercentOfFacility")


class ReposReposCurrentStorageAllocations(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    storagename: Optional[str]
    purpose: Optional[str]
    rootfolder: Optional[str]
    gigabytes: Optional[float]
    inodes: Optional[float]


Repos.model_rebuild()
ReposRepos.model_rebuild()
