# Generated by ariadne-codegen
# Source: queries

from pydantic import Field

from .base_model import BaseModel


class RequestStatuses(BaseModel):
    request_statuses: list[str] = Field(alias="requestStatuses")
