# Generated by ariadne-codegen
# Source: queries

from pydantic import Field

from .base_model import BaseModel


class RequestTypes(BaseModel):
    request_types: list[str] = Field(alias="requestTypes")
