# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CoactRequestStatus, CoactRequestType, ComputeRequirement


class Requests(BaseModel):
    requests: Optional[list["RequestsRequests"]]


class RequestsRequests(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    reqtype: Optional[CoactRequestType]
    requestedby: Optional[str]
    timeofrequest: Optional[Any]
    eppn: Optional[str]
    username: Optional[str]
    preferred_user_name: Optional[str] = Field(alias="preferredUserName")
    reponame: Optional[str]
    facilityname: Optional[str]
    principal: Optional[str]
    start: Optional[Any]
    end: Optional[Any]
    clustername: Optional[str]
    chargefactor: Optional[float]
    storagename: Optional[str]
    computerequirement: Optional[ComputeRequirement]
    purpose: Optional[str]
    rootfolder: Optional[str]
    allocationid: Optional[Any]
    percent_of_facility: Optional[float] = Field(alias="percentOfFacility")
    burst_percent_of_facility: Optional[float] = Field(alias="burstPercentOfFacility")
    allocated: Optional[float]
    burst_allocated: Optional[float] = Field(alias="burstAllocated")
    gigabytes: Optional[float]
    inodes: Optional[float]
    shell: Optional[str]
    previous_name: Optional[str] = Field(alias="previousName")
    publichtml: bool
    notes: Optional[str]
    dontsendemail: Optional[bool]
    approvalstatus: Optional[CoactRequestStatus]
    canapprove: Optional[bool]
    canrefire: Optional[bool]


Requests.model_rebuild()
