# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CoactRequestStatus, CoactRequestType, ComputeRequirement


class RequestsView(BaseModel):
    requests: Optional[list["RequestsViewRequests"]]
    myreposandfacility: list["RequestsViewMyreposandfacility"]
    facilities: list["RequestsViewFacilities"]
    request_types: list[str] = Field(alias="requestTypes")
    request_statuses: list[str] = Field(alias="requestStatuses")


class RequestsViewRequests(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    reqtype: Optional[CoactRequestType]
    requestedby: Optional[str]
    timeofrequest: Optional[Any]
    eppn: Optional[str]
    username: Optional[str]
    preferred_user_name: Optional[str] = Field(alias="preferredUserName")
    reponame: Optional[str]
    facilityname: Optional[str]
    principal: Optional[str]
    allocationid: Optional[Any]
    clustername: Optional[str]
    storagename: Optional[str]
    previous_name: Optional[str] = Field(alias="previousName")
    purpose: Optional[str]
    percent_of_facility: Optional[float] = Field(alias="percentOfFacility")
    allocated: Optional[float]
    gigabytes: Optional[float]
    start: Optional[Any]
    end: Optional[Any]
    shell: Optional[str]
    publichtml: bool
    computerequirement: Optional[ComputeRequirement]
    approvalstatus: Optional[CoactRequestStatus]
    canapprove: Optional[bool]
    canrefire: Optional[bool]
    notes: Optional[str]
    audit: Optional[list["RequestsViewRequestsAudit"]]


class RequestsViewRequestsAudit(BaseModel):
    actedat: Optional[Any]
    actedby: Optional[str]
    notes: Optional[str]
    previous: Optional[CoactRequestStatus]


class RequestsViewMyreposandfacility(BaseModel):
    name: str
    facility: str


class RequestsViewFacilities(BaseModel):
    name: Optional[str]


RequestsView.model_rebuild()
RequestsViewRequests.model_rebuild()
