# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UserPosixGroupUpdate(BaseModel):
    user_posix_group_update: "UserPosixGroupUpdateUserPosixGroupUpdate" = Field(
        alias="userPosixGroupUpdate"
    )


class UserPosixGroupUpdateUserPosixGroupUpdate(BaseModel):
    uidnumber: Optional[int]
    primary_gid: Optional[int] = Field(alias="primaryGid")
    secondary_gid_numbers: list[int] = Field(alias="secondaryGidNumbers")
    synced_at: Optional[Any] = Field(alias="syncedAt")


UserPosixGroupUpdate.model_rebuild()
