# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UsersLookupFromService(BaseModel):
    users_lookup_from_service: list["UsersLookupFromServiceUsersLookupFromService"] = (
        Field(alias="usersLookupFromService")
    )


class UsersLookupFromServiceUsersLookupFromService(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    username: Optional[str]
    fullname: Optional[str]
    uidnumber: Optional[int]
    eppns: Optional[list[str]]
    preferredemail: Optional[str]
    shell: Optional[str]
    publichtml: bool
    isbot: bool


UsersLookupFromService.model_rebuild()
