# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UsersPosixSync(BaseModel):
    users_posix_sync: "UsersPosixSyncUsersPosixSync" = Field(alias="usersPosixSync")


class UsersPosixSyncUsersPosixSync(BaseModel):
    dry_run: bool = Field(alias="dryRun")
    total: int
    matched: int
    changed: int
    unknown_users: list[str] = Field(alias="unknownUsers")
    uid_mismatches: list[str] = Field(alias="uidMismatches")
    aborted: bool
    reason: Optional[str]
    synced_at: Optional[Any] = Field(alias="syncedAt")


UsersPosixSync.model_rebuild()
