# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UsersMatchingUserNames(BaseModel):
    users_matching_user_names: Optional[
        list["UsersMatchingUserNamesUsersMatchingUserNames"]
    ] = Field(alias="usersMatchingUserNames")


class UsersMatchingUserNamesUsersMatchingUserNames(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    username: Optional[str]
    fullname: Optional[str]
    uidnumber: Optional[int]
    preferredemail: Optional[str]


UsersMatchingUserNames.model_rebuild()
