# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UsersMatchingUserName(BaseModel):
    users_matching_user_name: Optional[
        list["UsersMatchingUserNameUsersMatchingUserName"]
    ] = Field(alias="usersMatchingUserName")


class UsersMatchingUserNameUsersMatchingUserName(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    username: Optional[str]
    fullname: Optional[str]
    uidnumber: Optional[int]
    preferredemail: Optional[str]


UsersMatchingUserName.model_rebuild()
