# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class UserPosixRefresh(BaseModel):
    user_posix_refresh: "UserPosixRefreshUserPosixRefresh" = Field(
        alias="userPosixRefresh"
    )


class UserPosixRefreshUserPosixRefresh(BaseModel):
    uidnumber: Optional[int]
    primary_gid: Optional[int] = Field(alias="primaryGid")
    secondary_gid_numbers: list[int] = Field(alias="secondaryGidNumbers")
    synced_at: Optional[Any] = Field(alias="syncedAt")


UserPosixRefresh.model_rebuild()
