# Generated by ariadne-codegen
# Source: queries

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class Whoami(BaseModel):
    whoami: "WhoamiWhoami"


class WhoamiWhoami(BaseModel):
    id: Optional[Any] = Field(alias="Id")
    username: Optional[str]
    fullname: Optional[str]
    uidnumber: Optional[int]
    eppns: Optional[list[str]]
    preferredemail: Optional[str]
    shell: Optional[str]
    publichtml: bool
    isbot: bool
    facilities: list[str]
    is_admin: bool = Field(alias="isAdmin")
    is_czar: bool = Field(alias="isCzar")
    subject_facilities: list[str] = Field(alias="subjectFacilities")
    is_impersonating: bool = Field(alias="isImpersonating")
    groups: list[str]
    earliest_completed_user_account_registration: Optional[Any] = Field(
        alias="earliestCompletedUserAccountRegistration"
    )


Whoami.model_rebuild()
